---
- name: "Debian | package control | ensure package dirs owner and permissions"
  file:
    state: directory
    path: "{{ item }}"
    mode: "u=rwx,g=rx,o=rx"
    owner: "{{ sublime_package_control_owner }}"
    group: "{{ sublime_package_control_group }}"
  with_items:
    - "{{ __deb_pc_dir }}"
    - "{{ __deb_pc_user_dir }}"

- name: "Debian | package control | ensure 'Package Control.sublime-package' is present"
  get_url:
    url: "{{ __pc_url }}"
    dest: "{{ __deb_pc_dir }}/Package Control.sublime-package"
    mode: "u=rw,g=rw,o=rw"
    owner: "{{ sublime_package_control_owner }}"
    group: "{{ sublime_package_control_group }}"

- name: "Debian | package control | generate 'Package Control.sublime-settings'"
  template:
    src: ../templates/Package Control.sublime-settings.j2
    dest: "{{ __deb_pc_user_dir }}/Package Control.sublime-settings"
    mode: "u=rw,g=rw,o=rw"
    owner: "{{ sublime_package_control_owner }}"
    group: "{{ sublime_package_control_group }}"
    backup: "{{ sublime_package_control_backup }}"
